services:
    client:
        build: ./client
        ports: 
            - 3000:3000
        volumes: 
            - ./client/src/:/app/src/
    server:
        build: ./server
        ports: 
            - 8080:8000
    mongodb:
        image: mongo